import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tech Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.topNav}>
        <ul>
          <li><Link href={'/home'}>Home</Link></li>
          <li><Link href={'/about'}>About</Link></li>
          <li><Link href={'/blogs'}>Blogs</Link></li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1>Tech Blog</h1>
        <p className={styles.headDescription}>Next Js Blog</p>   
        <div className={styles.center}>
          <div className={styles.blogs}>
            <h2>Popular Blogs</h2>
            <div className="blogItems">
              <h3>What is Next Js?</h3>
              <p>It's a fremework of React.</p>
            </div>
            <div className="blogItems">
              <h3>What is Next Js?</h3>
              <p>It's a fremework of React.</p>
            </div>
            <div className="blogItems">
              <h3>What is Next Js?</h3>
              <p>It's a fremework of React.</p>
            </div>
            <div className="blogItems">
              <h3>What is Next Js?</h3>
              <p>It's a fremework of React.</p>
            </div>
            
           </div>
        </div>
      </main>
    </>
  )
}
